language: ruby
rvm:
 - 2.3.1

env: 
  - RAILS_ENV=test

services:
  - postgresql

before_script:
  - psql -c 'create database diy_assistant_test;' -U postgres

script: 
  - bundle exec rake db:migrate RAILS_ENV=test
  - bundle exec rake db:seed RAILS_ENV=test
  - bundle exec rake db:reset RAILS_ENV=test
  # - bundle exec rake spec

after_success:
  - gem install coveralls
  - CI=true TRAVIS=true coveralls --verbose
